### ISSUE TITLE
ERROR: suspend interval changing is not allowed for your account

### ISSUE THREAD

**Issue by YahiaElTai** [neondatabase/create-branch-action#31]
## Steps to reproduce

I'm currently on the free plan of Neon and I followed this guide by neon https://neon.tech/blog/branching-with-preview-environments to enable branching for Vercel previews.

I just updated to v4 of this action and started seeing this error. v3 was working perfectly.

```sh
ERROR: branch creation failed
ERROR: suspend interval changing is not allowed for your account
```

Here's my usage

```yml
      - name: Create Neon database branch
        uses: neondatabase/create-branch-action@v4
        id: create_branch
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{steps.get_pull_request_sha.outputs.pull_request_sha}}
          username: ${{ secrets.PG_USERNAME }}
          api_key: ${{ secrets.NEON_API_KEY }}
```
