### ISSUE TITLE
Allow action to create endpoint as well as branch.

### ISSUE THREAD

**Issue by nicksrandall** [neondatabase/create-branch-action#4]
It would be great if this action could create an endpoint along with the branch so that I can connect to the newly created branch.

My use case is that when I deploy to our staging environment, I would love to create a branch and configure my staging app to connect to it. 

It would also be nice if this action had the ability to delete a branch. That way I could clean up the old branches when changes have been approved.

**Comment by raoufchebri** [comment]
Hi @nicksrandall,
We just updated the outputs for the create-branch action. It now returns the db_url and the host in addition to the branch_id.
```
outputs:
  db_url:
    description: "New branch DATABASE_URL"
    value: ${{ steps.create-branch.outputs.db_url }}
  host:
    description: "New branch host"
    value: ${{ steps.create-branch.outputs.host }}
  ```
