### ISSUE TITLE
Possibly remove all required variables and assume NEON_ env variables

### ISSUE THREAD

**Issue by clarkbw** [neondatabase/create-branch-action#49]
Looking at https://github.com/neondatabase/preview-branches-with-fly/blob/main/.github/workflows/deploy-preview.yml 

The action pulls out env variables at the very top and yet it needs to specify them again with the action, duplicating the info. Actions can't dig into secrets on their own AFAIK but I think we could assume that any `NEON_` env variables belong to us such that we don't need required variables in our action. 

```yaml
env:
  NEON_DATABASE_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }} # change this to your database username
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required for commenting on pull requests for private repos
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }} # You can generate a an API key in your account settings
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }} # You can find this in your project settings
settings
```

If the required env variables aren't supplied we'd need to error out of course, so the shell script would still need to check for them and the args. And I'd assume the args take precedence over any env variables.

Example that assumes env variables:

```yaml
name: Create Neon Branch with GitHub Actions Demo
run-name: Create a Neon Branch 🚀
env:
  NEON_USERNAME: ${{ secrets.NEON_DATABASE_USERNAME }} # change this to your database username
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }} # You can generate a an API key in your account settings
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }} # You can find this in your project settings
settings

jobs:
  create-neon-branch:
    uses: neondatabase/create-branch-action@v5
    id: create-branch
  - run: echo db_url ${{ steps.create-branch.outputs.db_url }}
  - run: echo host ${{ steps.create-branch.outputs.host }}
  - run: echo branch_id ${{ steps.create-branch.outputs.branch_id }}
```
